# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_template-v2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_frame = QtWidgets.QFrame(self.centralwidget)
        self.left_frame.setGeometry(QtCore.QRect(-1, -1, 171, 491))
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.dir_lbl = QtWidgets.QLabel(self.left_frame)
        self.dir_lbl.setGeometry(QtCore.QRect(20, 10, 121, 21))
        self.dir_lbl.setObjectName("dir_lbl")
        self.song_list_lbl = QtWidgets.QLabel(self.left_frame)
        self.song_list_lbl.setGeometry(QtCore.QRect(20, 70, 81, 20))
        self.song_list_lbl.setObjectName("song_list_lbl")
        self.song_list = QtWidgets.QListView(self.left_frame)
        self.song_list.setGeometry(QtCore.QRect(20, 90, 111, 321))
        self.song_list.setObjectName("song_list")
        self.next_btn = QtWidgets.QPushButton(self.left_frame)
        self.next_btn.setGeometry(QtCore.QRect(90, 440, 61, 23))
        self.next_btn.setObjectName("next_btn")
        self.prev_btn = QtWidgets.QPushButton(self.left_frame)
        self.prev_btn.setGeometry(QtCore.QRect(20, 440, 61, 23))
        self.prev_btn.setObjectName("prev_btn")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.left_frame)
        self.verticalScrollBar.setGeometry(QtCore.QRect(130, 90, 21, 321))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setInvertedAppearance(False)
        self.verticalScrollBar.setInvertedControls(False)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.left_box = QtWidgets.QGroupBox(self.left_frame)
        self.left_box.setGeometry(QtCore.QRect(10, 10, 161, 461))
        self.left_box.setTitle("")
        self.left_box.setObjectName("left_box")
        self.dir_set_btn = QtWidgets.QPushButton(self.left_box)
        self.dir_set_btn.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.dir_set_btn.setObjectName("dir_set_btn")
        self.left_box.raise_()
        self.dir_lbl.raise_()
        self.song_list_lbl.raise_()
        self.song_list.raise_()
        self.next_btn.raise_()
        self.prev_btn.raise_()
        self.verticalScrollBar.raise_()
        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setGeometry(QtCore.QRect(170, 10, 481, 191))
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.name_lbl = QtWidgets.QLabel(self.top_frame)
        self.name_lbl.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.name_lbl.setObjectName("name_lbl")
        self.title_lbl = QtWidgets.QLabel(self.top_frame)
        self.title_lbl.setGeometry(QtCore.QRect(20, 50, 181, 16))
        self.title_lbl.setObjectName("title_lbl")
        self.artist_lbl = QtWidgets.QLabel(self.top_frame)
        self.artist_lbl.setGeometry(QtCore.QRect(20, 90, 181, 16))
        self.artist_lbl.setObjectName("artist_lbl")
        self.cur_img = QtWidgets.QLabel(self.top_frame)
        self.cur_img.setGeometry(QtCore.QRect(330, 20, 121, 111))
        self.cur_img.setAutoFillBackground(True)
        self.cur_img.setText("")
        self.cur_img.setObjectName("cur_img")
        self.top_box = QtWidgets.QGroupBox(self.top_frame)
        self.top_box.setGeometry(QtCore.QRect(0, 0, 481, 191))
        self.top_box.setTitle("")
        self.top_box.setObjectName("top_box")
        self.top_box.raise_()
        self.name_lbl.raise_()
        self.title_lbl.raise_()
        self.artist_lbl.raise_()
        self.cur_img.raise_()
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(170, 200, 481, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.left_img_frame = QtWidgets.QFrame(self.frame)
        self.left_img_frame.setGeometry(QtCore.QRect(0, 0, 241, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.left_img_frame.setPalette(palette)
        self.left_img_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_img_frame.setObjectName("left_img_frame")
        self.img_left = QtWidgets.QLabel(self.left_img_frame)
        self.img_left.setGeometry(QtCore.QRect(60, 40, 121, 111))
        self.img_left.setAutoFillBackground(True)
        self.img_left.setText("")
        self.img_left.setObjectName("img_left")
        self.left_img_title = QtWidgets.QLabel(self.left_img_frame)
        self.left_img_title.setGeometry(QtCore.QRect(90, 10, 91, 16))
        self.left_img_title.setObjectName("left_img_title")
        self.left_artist_lbl = QtWidgets.QLabel(self.left_img_frame)
        self.left_artist_lbl.setGeometry(QtCore.QRect(10, 210, 111, 16))
        self.left_artist_lbl.setObjectName("left_artist_lbl")
        self.lef_artist_edit = QtWidgets.QLineEdit(self.left_img_frame)
        self.lef_artist_edit.setGeometry(QtCore.QRect(80, 210, 113, 20))
        self.lef_artist_edit.setObjectName("lef_artist_edit")
        self.left_title_edit = QtWidgets.QLineEdit(self.left_img_frame)
        self.left_title_edit.setGeometry(QtCore.QRect(80, 170, 113, 20))
        self.left_title_edit.setObjectName("left_title_edit")
        self.left_title_lbl = QtWidgets.QLabel(self.left_img_frame)
        self.left_title_lbl.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.left_title_lbl.setObjectName("left_title_lbl")
        self.left_set_btn = QtWidgets.QPushButton(self.left_img_frame)
        self.left_set_btn.setGeometry(QtCore.QRect(90, 240, 61, 23))
        self.left_set_btn.setObjectName("left_set_btn")
        self.left_img_box = QtWidgets.QGroupBox(self.left_img_frame)
        self.left_img_box.setGeometry(QtCore.QRect(0, 0, 241, 271))
        self.left_img_box.setTitle("")
        self.left_img_box.setObjectName("left_img_box")
        self.left_img_box.raise_()
        self.img_left.raise_()
        self.left_img_title.raise_()
        self.left_artist_lbl.raise_()
        self.lef_artist_edit.raise_()
        self.left_title_edit.raise_()
        self.left_title_lbl.raise_()
        self.left_set_btn.raise_()
        self.right_img_frame = QtWidgets.QFrame(self.frame)
        self.right_img_frame.setGeometry(QtCore.QRect(240, 0, 241, 281))
        self.right_img_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_img_frame.setObjectName("right_img_frame")
        self.right_img_title = QtWidgets.QLabel(self.right_img_frame)
        self.right_img_title.setGeometry(QtCore.QRect(90, 10, 91, 16))
        self.right_img_title.setObjectName("right_img_title")
        self.right_title_lbl = QtWidgets.QLabel(self.right_img_frame)
        self.right_title_lbl.setGeometry(QtCore.QRect(10, 170, 91, 16))
        self.right_title_lbl.setObjectName("right_title_lbl")
        self.right_artist_edit = QtWidgets.QLineEdit(self.right_img_frame)
        self.right_artist_edit.setGeometry(QtCore.QRect(80, 210, 113, 20))
        self.right_artist_edit.setObjectName("right_artist_edit")
        self.right_title_edit = QtWidgets.QLineEdit(self.right_img_frame)
        self.right_title_edit.setGeometry(QtCore.QRect(80, 170, 113, 20))
        self.right_title_edit.setObjectName("right_title_edit")
        self.right_set_btn = QtWidgets.QPushButton(self.right_img_frame)
        self.right_set_btn.setGeometry(QtCore.QRect(90, 240, 61, 23))
        self.right_set_btn.setObjectName("right_set_btn")
        self.right_img_box = QtWidgets.QGroupBox(self.right_img_frame)
        self.right_img_box.setGeometry(QtCore.QRect(0, 0, 241, 271))
        self.right_img_box.setTitle("")
        self.right_img_box.setObjectName("right_img_box")
        self.right_artist_lbl = QtWidgets.QLabel(self.right_img_box)
        self.right_artist_lbl.setGeometry(QtCore.QRect(10, 210, 111, 16))
        self.right_artist_lbl.setObjectName("right_artist_lbl")
        self.right_img = QtWidgets.QLabel(self.right_img_box)
        self.right_img.setGeometry(QtCore.QRect(60, 40, 121, 111))
        self.right_img.setAutoFillBackground(True)
        self.right_img.setText("")
        self.right_img.setObjectName("right_img")
        self.right_img_box.raise_()
        self.right_img_title.raise_()
        self.right_title_lbl.raise_()
        self.right_artist_edit.raise_()
        self.right_title_edit.raise_()
        self.right_set_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 21))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        self.menuUpdate_artists_list = QtWidgets.QMenu(self.menumenu)
        self.menuUpdate_artists_list.setObjectName("menuUpdate_artists_list")
        self.menuRename_songs = QtWidgets.QMenu(self.menumenu)
        self.menuRename_songs.setObjectName("menuRename_songs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate_defult_dir = QtWidgets.QAction(MainWindow)
        self.actionCreate_defult_dir.setObjectName("actionCreate_defult_dir")
        self.actionThis_Directory = QtWidgets.QAction(MainWindow)
        self.actionThis_Directory.setObjectName("actionThis_Directory")
        self.actionSelect_directory = QtWidgets.QAction(MainWindow)
        self.actionSelect_directory.setObjectName("actionSelect_directory")
        self.actionAuto_Update = QtWidgets.QAction(MainWindow)
        self.actionAuto_Update.setObjectName("actionAuto_Update")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionView_And_Edit_Phrases = QtWidgets.QAction(MainWindow)
        self.actionView_And_Edit_Phrases.setObjectName("actionView_And_Edit_Phrases")
        self.actionAdd_Artist = QtWidgets.QAction(MainWindow)
        self.actionAdd_Artist.setObjectName("actionAdd_Artist")
        self.actionFind_All_Cover_Art = QtWidgets.QAction(MainWindow)
        self.actionFind_All_Cover_Art.setObjectName("actionFind_All_Cover_Art")
        self.menuUpdate_artists_list.addAction(self.actionAuto_Update)
        self.menuUpdate_artists_list.addAction(self.actionAdd_Artist)
        self.menuRename_songs.addSeparator()
        self.menuRename_songs.addAction(self.actionThis_Directory)
        self.menuRename_songs.addAction(self.actionSelect_directory)
        self.menuRename_songs.addSeparator()
        self.menuRename_songs.addAction(self.actionView_And_Edit_Phrases)
        self.menuRename_songs.addSeparator()
        self.menuRename_songs.addAction(self.actionFind_All_Cover_Art)
        self.menumenu.addAction(self.menuUpdate_artists_list.menuAction())
        self.menumenu.addAction(self.menuRename_songs.menuAction())
        self.menumenu.addSeparator()
        self.menumenu.addAction(self.actionCreate_defult_dir)
        self.menumenu.addSeparator()
        self.menumenu.addAction(self.actionExit)
        self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dir_lbl.setText(_translate("MainWindow", "Directory value"))
        self.song_list_lbl.setText(_translate("MainWindow", "Songs List"))
        self.next_btn.setText(_translate("MainWindow", "Next"))
        self.prev_btn.setText(_translate("MainWindow", "Previous"))
        self.dir_set_btn.setText(_translate("MainWindow", "Select Directory"))
        self.name_lbl.setText(_translate("MainWindow", "Song Name"))
        self.title_lbl.setText(_translate("MainWindow", "Title :"))
        self.artist_lbl.setText(_translate("MainWindow", "Artist"))
        self.left_img_title.setText(_translate("MainWindow", "Recomended"))
        self.left_artist_lbl.setText(_translate("MainWindow", "Artist"))
        self.left_title_lbl.setText(_translate("MainWindow", "Title :"))
        self.left_set_btn.setText(_translate("MainWindow", "Set"))
        self.right_img_title.setText(_translate("MainWindow", "Self Editing"))
        self.right_title_lbl.setText(_translate("MainWindow", "Title :"))
        self.right_set_btn.setText(_translate("MainWindow", "Set"))
        self.right_artist_lbl.setText(_translate("MainWindow", "Artist"))
        self.menumenu.setTitle(_translate("MainWindow", "Options"))
        self.menuUpdate_artists_list.setTitle(_translate("MainWindow", "Update Artists List"))
        self.menuRename_songs.setTitle(_translate("MainWindow", "Rename Songs"))
        self.actionCreate_defult_dir.setText(_translate("MainWindow", "Select Defult Dir"))
        self.actionThis_Directory.setText(_translate("MainWindow", "This Directory"))
        self.actionSelect_directory.setText(_translate("MainWindow", "Select Directory"))
        self.actionAuto_Update.setText(_translate("MainWindow", "Auto Update"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionView_And_Edit_Phrases.setText(_translate("MainWindow", "View And Edit Phrases"))
        self.actionAdd_Artist.setText(_translate("MainWindow", "Add Artist"))
        self.actionFind_All_Cover_Art.setText(_translate("MainWindow", "Find All Cover Art"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
